### ISSUE TITLE
Sink doesn't work with AppSettings

### ISSUE THREAD

**Issue by lukos** [chappoo/serilog-sinks-amazonses#2]
I cannot get this work due to the constructor not taking individual parameters, which means it cannot be automatically loaded from AppSettings.

I tried to copy the code and build a local library with another extension method but it doesn't work because the AmazonSimpleEmailServiceClient is not created anywhere in code and not documented about how it is supposed to be created.

I can guess and hack something around, but it would be good if either the docs matched the code (if the code is correct) or if the code was updated to work as per the docs.

**Comment by chappoo** [comment]
Thanks for raising. As is commonly the case, it's been a long time since I worked on this.  Will try to make some time to address this week.

**Comment by lukos** [comment]
I have some code that works that I am happy to share/PR depending on the plan. It is just another extension method that accepts separate parameters, creates a Config object and calls the other method.

**Comment by chappoo** [comment]
My preference is to keep the extension simple and drop the Config poco, something like:

```
var logger = new LoggerConfiguration()
    .WriteTo.AmazonSimpleEmailService(
        new AmazonSimpleEmailServiceClient(),
        emailFrom = "no-reply@myapp.com",
        emailTo = "test@test.com",
        emailSubject = "MyApp Warnings / Errors",
        restrictedToMinimumLevel: LogEventLevel.Warning
    )
    .CreateLogger();
```

Would that do the job?

**Comment by lukos** [comment]
I don't think it would work from AppSettings because it wouldn't support the SES Client object (and you would need to give that the AWS key and secret anyway). The way I did it just separates out the parameters and creates the client inside the Extension method. You could add more logic to allow e.g. key and secret to come from environment variables and can default any parameters that you don't want to make it as simple as possible.

**Comment by chappoo** [comment]
For AWS credential management it would be better to fall back to the SDKs discovery mechanisms, i.e: https://docs.aws.amazon.com/sdk-for-net/v2/developer-guide/net-dg-config-creds.html. 

Having to support the various options of the Amazon SES Client constructor overloads will get messy quickly, i.e. customising Regions, session tokens.  Much better to just define an AWS profile / envvars and let the AWS SDK do the work.

If you look at the [Kinesis sink](https://github.com/serilog/serilog-sinks-amazonkinesis/blob/master/src/Serilog.Sinks.Amazon.Kinesis/Firehose/KinesisFirehoseLoggerConfigurationExtensions.cs) logger extension overloads, that's the way they've done it, most likely for the same reasons.

**Comment by chappoo** [comment]
Re: configuration via AppSettings.  I'm not really across how that works as it's never been an approach I've investigated; is there some kind of auto mapping that takes place when calling CreateLogger()?

Does it depend on the signature of the extension method?

**Comment by lukos** [comment]
The appsettings stuff happens as a blanket function that will attempt to apply all appsettings that begin with serilog to logger configuration. It works with named parameters but only things that can be implicitly cast from the strings in the web config. In your case, the appsettings might look like:

```xml
<add key="serilog:using:AmazonSimpleEmailService" value="Serilog.Sinks.AmazonSimpleEmailService" />
<add key="serilog:write-to:AmazonSimpleEmailService.fromEmail" value="from@example.com" />
<add key="serilog:write-to:AmazonSimpleEmailService.restrictedToMinimumLevel" value="Error" />
<add key="serilog:write-to:AmazonSimpleEmailService.emailSubject" value="My subject" />
<add key="serilog:write-to:AmazonSimpleEmailService.toEmail" value="someone@example.com" />
<add key="serilog:write-to:AmazonSimpleEmailService.awsAccessKeyId" value="whatever" />
<add key="serilog:write-to:AmazonSimpleEmailService.awsSecretKey" value="whatever" />
<add key="serilog:write-to:AmazonSimpleEmailService.regionEndpoint" value="eu-west-1" />
```
The parameter names are simply the names of the parameters in the extension method. Not all sinks work with appsettings so I'm not sure how the Kinesis one would work.

**Comment by chappoo** [comment]
Have you tested the code with the overload to ensure that the AppSettings reader manages to pick the correct extension method overload?  I know this project is lacking any automated tests...

**Comment by chappoo** [comment]
@lukos I'm about to publish a new prerelease package (will take a few minutes to publish) with additional overloads that should support AppSettings covering your use-case (see linked PR).  I'd be interested to hear back on overload selection with AppSettings...

Feel free to test and report back on anything I may have overlooked... (including other improvements that might benefit the wider community).

**Comment by lukos** [comment]
Yes, it does work. In my local library, it's your code with another overload and it manages to find it. I'm not sure whether it tries them all in turn to see if any have all the parameters present. 
[AppSettings](https://github.com/serilog/serilog/wiki/AppSettings) seems to say that it will automatically expand env variables in AppSettings so that would be a way to handle getting aws secrets from the env instead of directly in code or config.

**Comment by chappoo** [comment]
https://www.nuget.org/packages/Serilog.Sinks.AmazonSimpleEmailService/2.0.0-feature000143 has just been indexed on nuget.org.  Once you've verified it's working with AppSettings, I'll merge in and release 2.0.0.  I'll also do some work on some automated tests to make sure this is covered during the build.

**Comment by chappoo** [comment]
V2.0 published

**Comment by lukos** [comment]
I have just got round to testing this with dotnet core appsettings.json and it works great, thanks!
