### ISSUE TITLE
NuGet Package doesn't work in .Net 4.5

### ISSUE THREAD

**Issue by lukos** [chappoo/serilog-sinks-amazonses#3]
The version 0.1.1 no longer works in .Net 4.6 because it requires very old versions of Serilog.

Version 2.0 doesn't work in .Net45 and requires the project to be upgraded to 4.6 and also requires the "Include prerelease" box to be ticked which is less than ideal.

If 0.1 is dead, please remove it from NuGet and release 2.0. It would also be good if it was targetted at 4.5 unless it really needs stuff from 4.6 (or even make it portable).

**Comment by chappoo** [comment]
The feature/2.0.0 branch is very much a work in progress and will be the next version released, but it's not in a release ready state yet.  Am planning on making the library support netstandard as well (lowest possible).

**Comment by chappoo** [comment]
Targeting net45 should be fine in the interim.  Longer term I think porting to netstandard1.0 is also possible which will keep support for net45 or above (as per https://github.com/dotnet/standard/blob/master/docs/versions.md)

**Comment by chappoo** [comment]
Minimum netstandard1.3, due to AWS SDKs.  Kept explicit support for net45 using multi-targeting.

**Comment by chappoo** [comment]
Done in PR #4
